### ISSUE TITLE
Issue while installing TF-comb

### ISSUE THREAD

**Issue by VenkateshLab** [loosolab/TF-COMB#61]
Im trying to install TF-comb using mamba i'm facing an error saying 
Could not solve for environment specs
```
mamba create -n tfcomb_env --file required_packages.txt
The following packages are incompatible
├─ pybigwig   does not exist (perhaps a typo or a missing channel);
├─ pysam   does not exist (perhaps a typo or a missing channel);
├─ tobias   does not exist (perhaps a typo or a missing channel);
└─ uropa   does not exist (perhaps a typo or a missing channel).
```
![Screenshot 2023-04-27 at 11 51 40](https://user-images.githubusercontent.com/118877790/234776933-45db49c2-f474-441b-ae94-b3f0082a30f5.png)

while trying to installing using pip
`pip install TF-COMB`

im facing an error with matlab 
![Screenshot 2023-04-27 at 11 58 17](https://user-images.githubusercontent.com/118877790/234778063-f8e7383d-53ad-4465-821e-da82983e36a6.png)

can you help to fix this issue.

**Comment by vheger** [comment]
Hi @VenkateshLab,

thank you for your interest in TF-COMB. 

Regarding the **mamba** issue: it seems like you missing the `bioconda` channel on your mamba installation, can you please try 
`mamba create -n tfcomb_env --file required_packages.txt --channel bioconda`  and see if it works for you? 

Regarding the **matplotlib** Issue: can you please check you matplotlib version, e.g. with `pip show matplotlib` ? If it's below 3.6.0 you will encounter this deprecation warning. Updating matplotlib to a version above 3.6.0 should make the warning disappear. 
However you should be able to use tfcomb besides the warning. Can you please try ` tfcomb.__version__`  after the warning? like 
```
>>> import tfcomb
/python3.9/site-packages/tfcomb/network.py:16: MatplotlibDeprecationWarning:
The mpl_toolkits.axes_grid module was deprecated in Matplotlib 2.1 and will be removed two minor releases later. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist, which provide the same functionality instead.
  from mpl_toolkits.axes_grid.inset_locator import inset_axes
>>> tfcomb.__version__
'1.0.3'
```
If you see a version like 1.0.3 you could proceed with the usage of tfcomb. 
Please note we highly recommend to use the newest version, if you see a version below 1.0.3 please consider updating tfcomb as well.

I hope this solves your problem, if not please let me know and I'm happy to assist you further.

**Comment by vheger** [comment]
Hi ! 

I can not see the folder you are executing python from. Are you executing python from within the TF-COMB folder ?
For the mamba installation: After `pip install .` can you try moving to another folder (e.g. one folder up)?   
The reason for this is: the python interpreter tries to import the local module from the folder you are in instead of the installed module (see my attached screenshot). 
![Issue61](https://user-images.githubusercontent.com/85618292/234848477-9b994518-8ccb-426f-87cb-cc8f019f41ea.PNG)

The same problem exists when installed via pip but python is executed from within the TF-COMB folder.

I see this is a caveat we should mention in the installation section,  I will update our Readme accordingly, thank you.

If this does not solve the problem in your case, please let me know.
