### ISSUE TITLE
Details about subsetting TF-TF co-occurring pairs 

### ISSUE THREAD

**Issue by Myrtle-bio** [loosolab/TF-COMB#72]
Hello! 

In the research article, you mentioned: 
_By subsetting pairs based on cosine score and significance (Zscore) across all 8 cell lines, we were able to specify a total of 1938 (1877 unique) TF-TF co-occurring pairs, which correspond to 1–3% of all pairs per cell line._

Could you explain the cutoffs used in your study? For the different cell lines, did you select a consistent cosine and significance score as your cutoff, or did you choose, for example, select the TF pairs based on the top 10% of cosine scores and significance scores for each cell line?

Thanks a lot for your work!

**Comment by vheger** [comment]
Although it appears this Issue is already solved on it's own, which is great, I will answer the main points shortly for later reference. 

**Could you explain the cutoffs used in your study?** 
In our study we used fixed cutoffs of `0.3` for **_cosine_** and `50` for **_Z-score_** consistent in all 8 cell lines, in order to compare between them. Depending on the cell line this yielded between 1-3% of the pairs as significant. For example in cell line _GM12878_ **148** pairs were selected significant which corresponds to **~2.7 %** of possible pairs whereas in _MCF-7_  **43** pairs were selected significant which corresponds to **~1.4 %**.  

**did you select a consistent cosine and significance score as your cutoff [...]?**
Yes we selected consistent thresholds, in order to archive comparability. 

**Additional comment**
We recommend that the thresholds should generally be set depending on what question is being asked, meaning it depends per dataset and research question what should be selected.

**Comment by Myrtle-bio** [comment]
Thanks a lot to your reply!
